### ISSUE TITLE
project dropdown on event page does not reset after you filter and then hit back button

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1022]
![](https://www.dropbox.com/s/9aoawqh6xh9woud/Screenshot%202016-05-04%2017.11.56.png?dl=1)

**Comment by mattwr18** [comment]
Filtered list of events for WebsiteOne:
![screenshot at 2018-10-18 16 37 58](https://user-images.githubusercontent.com/26943915/47179365-47028200-d2f4-11e8-93c8-db5281fc68b4.png)
Back button correctly shows all future events, but the dropdown maintains the filter params instead of defaulting to `All`:
![screenshot at 2018-10-18 16 38 24](https://user-images.githubusercontent.com/26943915/47179448-74e7c680-d2f4-11e8-8bc0-481ee736ee8e.png)

**Comment by mattwr18** [comment]
@cess is working on this :)

**Comment by tansaku** [comment]
@mattwr18 do we have her assigned? or maybe I need to add her to the team to get the assign option?

**Comment by cesswairimu** [comment]
Yeah @tansaku yeah I am not part of the team if you could add me to waffle that would be awesome :smiley. Thanks

**Comment by tansaku** [comment]
have invited you @cesswairimu :-)
