### ISSUE TITLE
link karma number to breakdown of karma on user profile page

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1245]
Would be good to be able to go from individual karma numbers on users index page to breakdown of karma on profile ... might be a little tricky due to currently having hyperlink on whole thing

**Comment by Maroo-b** [comment]
@tansaku I suggest to edit the hyperlink to user profile by setting it on user name and on his avatar only. The reason behind this even the whole block is clickable a user will try to point to the user name because it looks like a link.

**Comment by tansaku** [comment]
good idea @Maroo-b !

**Comment by Maroo-b** [comment]
@tansaku can you please provide me a link to breakdown of karma on profile is it the activity tab on profile ?

**Comment by tansaku** [comment]
@Maroo-b it is the activity tab on the profile

**Comment by Maroo-b** [comment]
@tansaku I was experimenting with development environment, and I noticed that it's possible to have users without activity tab in their profiles. So I think about two alternatives here:
1- To add link to karma number and in case the user doesn't have an Activity tab the system display the profile w a flash message "The user does not have Activity record yet" for example.

2- To add link only to users who have activity tab only. 

I prefer the first alternative because it keeps the consistency of the system and avoid making users guess why the link on Karma number isn't always present.

What do you think ?
