### ISSUE TITLE
investigate removing or replacing cubeportfolio.js/confy.js

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1283]
due to incompatible license

it's in vendor/assets/javascript

**Comment by mtc2013** [comment]
https://codecanyon.net/item/cube-portfolio-responsive-jquery-grid-plugin/6372959

**Comment by tochman** [comment]
Alright, now I remember. This library was used in the original design of the events index page. Not used since the spike so it should have been removed ages ago. I have a license for this code personally but it is not used so... My mistake, I should have removed it when I implemented another solution.
