### ISSUE TITLE
Time-picker's icons are not displayed on events create page (Again 😞)

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1354]
![](https://cl.ly/122D3Q1B2s2R/download/Screenshot%202016-10-22%2019.32.32.png)
## Steps to Reproduce (for bugs)
1. [Create new event](http://www.agileventures.org/events/new)
2. Set a time for the event
3. Note missing icons to increment/decrement

We've had this issue before see #755

**Comment by diraulo** [comment]
![screenshot 2016-10-25 16 41 33](https://cloud.githubusercontent.com/assets/4028374/19690782/12272cb8-9ad2-11e6-8c8e-7bc9722de89a.png)

**Comment by Maroo-b** [comment]
I was checking this issue, it seems that's related to moving the app assets dependencies to npm.

According to the docs in http://jdewit.github.io/bootstrap-timepicker/ it's possible to change via custom configs, but it didn't work. I opened a new issue it the github repo: https://github.com/jdewit/bootstrap-timepicker/issues/359 

The previous fix in #755 was possible because we have access to the timepicker source code in vendor.

**Comment by c1505** [comment]
Updating to the most recent bootstrap-timepicker fixes this.  I'll look to make sure it doesn't break anything else and submit a PR in the next day or two.
