### ISSUE TITLE
doc: Best practices/recommended git & github workflow

### ISSUE THREAD

**Issue by weedySeaDragon** [AgileVentures/WebsiteOne#1367]
Describe a recommended git/github workflow so that new projects have a starting point and so that developers new to AV understand the default git/github workflow. 
(@thessus and I had questions and couldn't find this documented on the AV site)

**Comment by tansaku** [comment]
good point @weedtSeaDragon and @thessus - I guess http://www.agileventures.org/getting-started is specific to joining a project rather than starting a project.

A "How to start a project" doc would be good.

@tochman did start work on some pathways docs at one point:

https://www.agileventures.org/projects/agileventures-community/documents/agileventures-paths

There are various stubs here https://www.agileventures.org/projects/agileventures-community/documents - would be good to bring everything up to date

**Comment by mattlindsey** [comment]
+1
