### ISSUE TITLE
[Airbrake] [Production] undefined method `display_name' for nil:NilClass Did you mean?  display

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#1505]
**Airbrake error:** [#4693](https://herokuapp21498474herokucom.airbrake.io/projects/117119/groups/1865905050398224693)
**Airbrake project:** websiteone-production

**Error type:** `NoMethodError`
**Error message:** `` undefined method `display_name' for nil:NilClass Did you mean?  display ``
**Where:** `rake#db:migrate_plans`
**Occurred at:** Jan 18, 2017 11:00:05 UTC
**First seen at:** Jan 18, 2017 11:00:05 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)

**URL:** `<no information>`
**File:** `[PROJECT_ROOT]/lib/tasks/migrate_plans.rake`

**Backtrace:**
```
[PROJECT_ROOT]/lib/tasks/migrate_plans.rake:9:in block (3 levels) in <top (required)>
[GEM_ROOT]/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in each
[GEM_ROOT]/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in each
[PROJECT_ROOT]/lib/tasks/migrate_plans.rake:5:in block (2 levels) in <top (required)>
```

**Comment by tansaku** [comment]
this was due to some subscriptions not having users associated with them - I fixed those manually

we could update the migration script to handle those situations better, but we're unlikely to use it again.

I guess we're getting to the point where we should insist on login to create subscriptions - then again - I don't want to force the new nonprofit org plan subscribers to have to log in through github or G+ ...
