### ISSUE TITLE
adjust premium description pages to have expandable info from headings

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1565]
Marufa suggested we have a faq popup for pages like http://www.agileventures.org/premium to make the pages shorter and easier to navigate - I think we can use detail/summary tags to achieve this.

https://www.w3schools.com/tags/tag_summary.asp

**Comment by tansaku** [comment]
```
As a site owner
So that I can sustain the site with revenue from Premium 
I would like for the overview of a plan to look concise and be easy to review, with more details available on click
As opposed to currently where all the text is laid out in one big go.
```

**Comment by tansaku** [comment]
I've done a mockup of a new version of an expandable list of Premium benefits here: http://websiteone-staging.herokuapp.com/premium

**Comment by weedySeaDragon** [comment]
It's great that you have the mockup.  It's always _so_ much easier to comment on a tangible example. :-) 

My main reaction is that you need to re-craft some of those items because they are answering the question "what"  but when describing a benefit, you want to answer **"WHY"** as in "Why would I care?  Why would this be helpful to me?"

Ex:

  -  **JetBrains Integrated Development Environment (IDE) licence (worth £15 a month)**

is really answering _what_.  Re-state it to provide the _why this is valuable_ right up front. (Then you can provide the _what_ details in the full description:

  -  **Free use of the full-powered RubyMine development software on your AgileVenture projects. (A £60/year value)**

That's a quick, rough example.  ("full-powered" should be replaced by something better.)  But you get the idea.
I would be happy to brainstorm with others on this if it's helpful. 


I would also suggest that you don't use bullets that expand.  You want all of that information to be there immediately!  You really do want your reader to see all of it; you don't want to hide it or have them do any additional steps to see it.  You're trying to convince them; you don't want any barriers whatsoever.  (Perhaps your mockup was just using some default CSS that does that and you don't really intend the final version to have it.)


Just like the 3 rule of buying real estate are "Location, location, location" the 3 rules of getting £ are "Benefit, benefit, benefit" :-)

**Comment by tansaku** [comment]
@weedySeaDragon love the re-wording - I've deployed that to http://www.agileventures.org/premium

feel free to add further changes to http://websiteone-staging.herokuapp.com/premium or indeed just write out other suggested re-wordings in another ticket (since this one is specifically for the popups - I've opened another for the re-wording #1583) - I agree that answering "why" rather than "what" would be a huge improvement

As regards the popup elements, that was something we settled on through a series of marketing meetings (you're welcome to join (maybe too early ...) or catch the videos - all in the #marketing channel).

I think one of the problems we have with the site is too much text all over the place - although that's an intuition rather than something that I can currently prove with hard data - although I suspect our bounce rate might improve if we reduced text length.

I take your point that "You want all of that information to be there immediately!", but I worry that when there's a lot of text in the page (as we have in many others), some people just click away in disgust, feeling overwhelmed with the text.

Well perhaps we can move towards A/B testing that and seeing what the Google Analytics tell us ...

**Comment by weedySeaDragon** [comment]
I totally agree about keeping things shorter and less overwhelming. My view is that on a page that is this important, you don't want the popups.  Instead you need to keep the text short and focused.

There are definitely places where popups are great. (ex: FAQs).

**Comment by tansaku** [comment]
Just discussed in Marketing and consensus is that "expandable" elements for faq is good and maybe just have two sentence headlines for feature and no extra description

**Comment by tansaku** [comment]
so I think I blew away changes we might have had on the staging server ... when I copied the production data over ...

**Comment by tansaku** [comment]
right, well I've updated the faq section on the production premium page: https://www.agileventures.org/premium#faq
