### ISSUE TITLE
minor text changes

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1587]
@federico suggested:

> In "Want to learn more? Listen in. Next projects review meeting in 2 hours 3 minutes"  projects should be project's

and in our scrum we just talked about making the home page button "Get started now to begin coding on real projects!"

**Comment by FedericoEsparza** [comment]
The added `on real projects` is perfect.

**Comment by FedericoEsparza** [comment]
@tansaku If I interpret the sentence correctly, it's a possessive of a singular noun, so it would require an apostrophe. Reworded, it could be "The next review meeting of a project." 
 
Perhaps your intended meaning is not what I assume it is, however.

**Comment by weedySeaDragon** [comment]
It should **not** have a comma.

`Next project's review meeting - listen in to learn more about AgileVentures`

Because `project` is a noun, it _could_ be capable of ownership and therefore be possessive.  But in this case it's not.

`[P]roject` is something that actually describes the meeting.  It's an _adjective._ One way to test that it to remove the word -- `project` in this case -- and see if the sentence or phrase still makes sense.  In this case, it does:

`The next review meeting....`

(And we can see that `review` is an adjective because we can remove it and the phrase would still make sense:  `The next meeting....`)

**But --  this discussion is proof that the phrase is not clear and should be reworded.** 

How about this:


`Here's the next project meeting  - listen in to learn more about AgileVentures`


We can't assume that the next event is a _review_.  It really could be a meeting about any number of things, right?

**More importantly:**  I think that "...to learn more about AgileVentures" is weak.    If you can answer _why would this help someone to learn about AV?_  then we can come up with something stronger.

**Comment by tansaku** [comment]
@FedericoEsparza @weedySeaDragon - multiple projects are discussed in each meeting, so I see it as strongly plural

**Comment by weedySeaDragon** [comment]
Excellent point, @tansaku .

How about something like:

`Here's the next meeting where we review many projects.  Listen in to learn more about AgileVentures`

or 

`Here's the next meeting reviewing many projects. Listen in to learn more about AgileVentures`

or 

`To learn more, listen in to the next meeting where we review many of our projects`

**Comment by federico** [comment]
> @federico suggested:

You tagged the wrong one.

**Comment by tansaku** [comment]
sorry @federico I meant @FedericoEsparza

**Comment by tansaku** [comment]
@ashley it's slightly complicated by the following text that will always say "in 2 hours 13 minutes" or "is starting now" - that can also be changed, but we're trying to get out a quick couple of improvements over what we had before.

Perhaps we can open a new ticket on the best text, given that the sentence also has the time/date start thing in it ...
