### ISSUE TITLE
automating offers of premium

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#1797]
System for identifying people likely to sign up for premium - we'd like to offer them a free months' trial of premium:

* could show banner in site
* could send email

in first instance maybe just send some emails? perhaps through elasticemail

**Comment by tansaku** [comment]
concern that we need to tack who actually opens the emails

**Comment by praveendhawan** [comment]
@tansaku Also as it happened to me, the promotional email end up in my spam folder, I would also suggest looking into that. We can setup a separate domain or try to push the reputation of the domain we are using so that it won't end up in someone's spam folder. That would make the tracking of emails opened meaningful.

**Comment by tansaku** [comment]
agreed @praveendhawan - I also have a suspicion that there are some MX settings or something that are poorly set for our gandi hosted domain - changes there might make an impact - we need a full analysis ...
