### ISSUE TITLE
Coveralls seems a little crazy

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2112]
thinking to switch to codeclimate coverage stats or fix coveralls ...

**Comment by nisevi** [comment]
We are exposing the `repo_token` [here](https://github.com/AgileVentures/WebsiteOne/blob/develop/.coveralls.yml) and that may be our issue since anyone can change our coveralls repo by running `bundle exec rake ci:test` or any variation of it that at the end performs the `coveralls:push`, I need your corroboration that this token is being configured on [caveralls website for websiteone](https://github.com/AgileVentures/WebsiteOne)

One posible solution is to build the file in the setup that semaphoreci performs, something like:

`echo "repo_token: ${COVERALLS_YML_TOKEN}" > .coveralls.yml`

would do the trick. Obviously we need to add this env variable `COVERALLS_YML_TOKEN` first.

And then we should remove this [file](https://github.com/AgileVentures/WebsiteOne/blob/develop/.coveralls.yml) from our tracking system?

**Comment by nisevi** [comment]
I mistakenly closed the issue when doing the comment I think.

**Comment by tansaku** [comment]
options:

1) further investigation of coveralls config
2) open support ticket with coveralls
3) add codeclimate coverage

**Comment by nisevi** [comment]
@tansaku Coveralls was removed, still displays as part as our CI checks.

**Comment by tansaku** [comment]
all fixed now
