### ISSUE TITLE
improve events page performance

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2118]
currently takes several seconds to load the events index page - from previous analysis my sense is that the time is spent in the ruby code generating the complete list of upcoming events from the recurring events.

We could improve performance by storing horizon of event data in the db up to six weeks and recalculating on edit, not on view ...

**Comment by tansaku** [comment]
I tried this but I get the following error:

![](https://dl.dropbox.com/s/ut6emahmel1zt8n/Screenshot%202018-11-12%2011.35.35.png?dl=0)

I added     

```rb
config.cache_store = :memory_store, { size: 64.megabytes }
```
to config/application.rb and running the following command to enable caching in development:

```
be rails dev:cache
```

**Comment by dkuku** [comment]
The problem might be in the next_occurrences method in Event model- when the time is far in the future it returns lots of events (100 ??) and you really want events for the next month (max 40 when daily event)

``` 
pry(main)> Event.last.repeat_ends_on                                                                           
  Event Load (0.7ms)  SELECT  "events".* FROM "events" ORDER BY "events"."id" DESC LIMIT $1  [["LIMIT", 1]]         
=> Thu, 21 Nov 2019
[23] pry(main)> Event.last.next_occurrences.count
  Event Load (0.6ms)  SELECT  "events".* FROM "events" ORDER BY "events"."id" DESC LIMIT $1  [["LIMIT", 1]]         
=> 100
```

I also tried to set index on - this gave me a small boost - but it's hard to tell because my data is mostly fake and repetive (but event page render and event.json takes over 1 second )
```
  def change
    add_index :events, :repeats
    add_index :events, :repeat_ends
    add_index :events, :repeat_ends_on
  end
```
