### ISSUE TITLE
Saving an Event's YouTube link pings Hangout Slack message

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne#2190]
![](https://dl.dropbox.com/s/c5w2n8yg8napxil/Screenshot%202018-02-28%2016.24.17.png)
![](https://dl.dropbox.com/s/jfk2s1rch3prrf1/Screenshot%202018-02-28%2016.29.08.png)
 
**Still posts properly** to the **project's video section**, however:
 
![](https://dl.dropbox.com/s/2bl8fqb1ttrby1x/Screenshot%202018-02-28%2016.44.49.png)

**Comment by tansaku** [comment]
is the issue here that the youtube link did not ping to the right channels?

**Comment by FedericoEsparza** [comment]
No.

It pings #general, which is fine.

The weird occurrence was that when adding and saving the YouTube link, it re-pinged the Hangout “click to join” message, NOT the “click to play” message.

I double-checked the actual “click to join” url that it re-pinged, and it was the Hangout link.
On Mar 2, 2018, at 4:21 AM, Sam Joseph <notifications@github.com<mailto:notifications@github.com>> wrote:


is the issue here that the youtube link did not ping to the right channels?

**Comment by tansaku** [comment]
@FedericoEsparza ah, super weird ... wonder if @nisevi could take a look at this ...

**Comment by nisevi** [comment]
@FedericoEsparza  @tansaku sure thing I will take a look :+1:

**Comment by tansaku** [comment]
@nisevi I just had an idea that it's because we don't have a rundfunk slack channel id in the slack service - I've added the thing we might need here: https://github.com/AgileVentures/WebsiteOne/pull/2203  but it also suggests that maybe we don't have good error handling for when a project doesn't have a specified slack channel

would be great to have tests for that and better error handling.

Ultimately what we'd really like is the ability for the project manager to specify which is the slack channel they use rather than hard coding as we do currently ...
