### ISSUE TITLE
Unable to reset my password

### ISSUE THREAD

**Issue by subratrout** [AgileVentures/WebsiteOne#2405]
When trying to reset password the link I get in my email is not working.

## Expected Behavior
The link should take me to the site to reset the password

## Current Behavior
However I am getting a link similar to this and the browser says unable to connect
https://agileventures.org/users/password/edit.username?reset_password_token=aRandomString

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by tansaku** [comment]
thanks for reporting this @subratrout - I think the issue is to do with our https set up - it can't handle the  link without the www. prefix - super short term fix for you would be to add www prefix in the URL and try visiting ...

we've got two levels of fixes our side which are:

1) adjust link to ensure it includes www. prefix
2) adjust our av.org domain configuration so that https://agileventures.org will work
