### ISSUE TITLE
automate emails to folks joining projects

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2537]
@maryam21 previously created a great feature (suggested by @FedericoEsparza #1813 ) where project managers are alerted by email to folks joining their projects.  

It's been really interesting to see who is signing up for which projects, and I'd love to see this feature extended so that the folks joining would also get an email welcoming them to the project.  At the moment I am doing this manually for the projects that I am managing, sending emails like this:

> Hi,

> Thanks so much for joining the WebSiteOne project - as you might know, it's the Rails code that powers our main site - we coordinate via #websiteone on slack and there's a #websiteone-install channel for help to get set up.

> Just reach out if there's anything you need

> Best, Sam 

I've love to automate these emails and give all the project managers the ability to set a default greeting template for them to include whatever info, links, greeting they thought would be good for newcomers to get.

**Comment by tansaku** [comment]
we're exploring the testing of emails here: https://github.com/rspec/rspec-rails/issues/2030#issuecomment-427648945

**Comment by tansaku** [comment]
might have solution here https://github.com/rspec/rspec-rails/issues/2030#issuecomment-428487405

**Comment by NickSchimek** [comment]
@aonomike and I worked through this today and read through the Rails Mailer documentation together. 
Here is a list of items we noted down that need to be addressed to complete the issue.

Tasks needed to complete issue.

- [ ] Create fixture for unit testing Mailer controller.
- [ ] Update `config/settings.yml` so that [URL's can be generated](https://guides.rubyonrails.org/action_mailer_basics.html#generating-urls-in-action-mailer-views) within the mailer.
- [ ] May need to add other items...

Refactoring items:

- [ ] Extract Project mailers into it's own controller class.
- [ ] Call Projects mailer controller directly from the Project controller.
- [ ] Pass the Projects mailer a params object instead of arguments. (This allows for dryer code among other things)

Reference Links

- [Action Mailer Callbacks](https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-callbacks)
- [Adding images in Action Mailer views](https://guides.rubyonrails.org/action_mailer_basics.html#adding-images-in-action-mailer-views)

**Comment by tansaku** [comment]
thanks @NickSchimek and @aonomike - any chance you might work on this again any time soon?

**Comment by NickSchimek** [comment]
@tansaku I just pushed a commit. will finish this up soon.
