### ISSUE TITLE
Get Amazon Smile banner up on our site

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#2608]
To help folks donate to us while shopping at Amazon:

```
<div id="amznCharityBanner"><script type="text/javascript">(function() {var iFrame = document.createElement('iframe'); iFrame.style.display = 'none'; iFrame.style.border = "none"; iFrame.width = 310; iFrame.height = 256; iFrame.setAttribute && iFrame.setAttribute('scrolling', 'no'); iFrame.setAttribute('frameborder', '0'); setTimeout(function() {var contents = (iFrame.contentWindow) ? iFrame.contentWindow : (iFrame.contentDocument.document) ? iFrame.contentDocument.document : iFrame.contentDocument; contents.document.open(); contents.document.write(decodeURIComponent("%3Cdiv%20id%3D%22amznCharityBannerInner%22%3E%3Ca%20href%3D%22https%3A%2F%2Fsmile.amazon.co.uk%2Fch%2F1170963-0%22%3E%3Cdiv%20class%3D%22text%22%20height%3D%22%22%3E%3Cdiv%20class%3D%22support-wrapper%22%3E%3Cdiv%20class%3D%22support%22%20style%3D%22font-size%3A%2025px%3B%20line-height%3A%2028px%3B%20margin-top%3A%2015px%3B%20margin-bottom%3A%201px%3B%22%3ESupport%20%3Cspan%20id%3D%22charity-name%22%20style%3D%22display%3A%20inline-block%3B%22%3EAgileVentures%20Charity%3C%2Fspan%3E%3C%2Fdiv%3E%3C%2Fdiv%3E%3Cp%20class%3D%22when-shop%22%3EWhen%20you%20shop%20at%20%3Cb%3Esmile.amazon.co.uk%2C%3C%2Fb%3E%3C%2Fp%3E%3Cp%20class%3D%22donates%22%3EAmazon%20Donates%3C%2Fp%3E%3C%2Fdiv%3E%3C%2Fa%3E%3C%2Fdiv%3E%3Cstyle%3E%23amznCharityBannerInner%7Bbackground-image%3Aurl(https%3A%2F%2Fm.media-amazon.com%2Fimages%2FG%2F02%2Fx-locale%2Fpaladin%2Fcharitycentral%2Fbanner-background-image._CB494422932_.png)%3Bwidth%3A302px%3Bheight%3A250px%3Bposition%3Arelative%7D%23amznCharityBannerInner%20a%7Bdisplay%3Ablock%3Bwidth%3A100%25%3Bheight%3A100%25%3Bposition%3Arelative%3Bcolor%3A%23000%3Btext-decoration%3Anone%7D.text%7Bposition%3Aabsolute%3Btop%3A20px%3Bleft%3A15px%3Bright%3A15px%3Bbottom%3A100px%7D.support-wrapper%7Boverflow%3Ahidden%3Bmax-height%3A86px%7D.support%7Bfont-family%3AArial%2Csans%3Bfont-weight%3A700%3Bline-height%3A28px%3Bfont-size%3A25px%3Bcolor%3A%23333%3Btext-align%3Acenter%3Bmargin%3A0%3Bpadding%3A0%3Bbackground%3A0%200%7D.when-shop%7Bfont-family%3AArial%2Csans%3Bfont-size%3A15px%3Bfont-weight%3A400%3Bline-height%3A25px%3Bcolor%3A%23333%3Btext-align%3Acenter%3Bmargin%3A0%3Bpadding%3A0%3Bbackground%3A0%200%7D.donates%7Bfont-family%3AArial%2Csans%3Bfont-size%3A15px%3Bfont-weight%3A400%3Bline-height%3A21px%3Bcolor%3A%23333%3Btext-align%3Acenter%3Bmargin%3A0%3Bpadding%3A0%3Bbackground%3A0%200%7D%3C%2Fstyle%3E")); contents.document.close(); iFrame.style.display = 'block';}); document.getElementById('amznCharityBanner').appendChild(iFrame); })(); </script></div>
```

**Comment by tansaku** [comment]
should look like this:

![](https://dl.dropbox.com/s/qjyard2hod44nfh/Screenshot%202018-08-30%2008.53.40.png?dl=0)

**Comment by dkuku** [comment]
Any suggestions on where to insert it?
I think that it may go below the supporters logos.

**Comment by tansaku** [comment]
@dkuku sounds good to me

**Comment by dkuku** [comment]
This banner was is 310px wide, other banners are around 210 - 215px wide, I unpacked the html and css from the script and updated the width - I also centered the image. The button is part of the image so a bit hard to adjust the position. 
Currently, all the data is inside the js file. I wonder if I should move this to separate files?
Also, I need some hints about testing, this is an iframe. I added target=_blank to the link because for some reason it was opening the page inside this 310x250 window.
Now it looks like this:
![amazon banner](https://user-images.githubusercontent.com/904179/46872924-59c91280-ce2d-11e8-9876-302c51df1bbc.png)

**Comment by tansaku** [comment]
this looks great @dkuku - for testing - can you see the existing sponsor tests? 

https://github.com/AgileVentures/WebsiteOne/blob/master/features/pages.feature#L26

are you familiar with how to run the cucumber tests?

**Comment by dkuku** [comment]
Thanks for the testing links. I can do this. 
My concern now is all the inline html and css inside the javascript file, which basically generates the iframe with the text on top of an background image that links to [https://smile.amazon.co.uk/ch/1170963-0](https://smile.amazon.co.uk/ch/1170963-0) - check the commit I made.

I made a second version which I think is better, where I pasted all the text "Support AgileVentures..." to the image and fixed the orange frame on the sides and spacing, now the image needs to be served from the assets folder but it takes less than 4kb instead of the old 6kb image + 2,5kb js.

**Comment by tansaku** [comment]
@dkuku thanks for all your work on this

We'll get this one merged in - perhaps you could open another ticket about the image optimisation and then put in a separate PR for that?

We'll also create a test refactoring issue based on robert's comments
