### ISSUE TITLE
Adding two events (same time, diff days) concurrently results in different times for each

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/WebsiteOne#2795]
In the "create event" form, I create an event that happens twice a week - Monday and Thursday - at 12:30 EDT (NY time).  The Monday event is showing on the calendar with the correct time.  The Thursday event shows a start time that is 1 hour earlier (11:30 am).  This is consistent behavior regardless of what start time I use for the events.

The is for the "SHF" project.  See screenshot.

<img width="656" alt="screen shot 2018-11-01 at 6 11 05 am" src="https://user-images.githubusercontent.com/9968213/47847067-832bed00-dda0-11e8-9bdc-428a6b312350.png">

**Comment by FedericoEsparza** [comment]
@patmbolger I think this is just due to the daylight saving clock changes going on this weekend in the U.S.
 
The site events stay on UTC time, which doesn't change; therefore, all the events are an hour earlier in our local time, starting next week.
 
Also, when I paused the events (with Susanna's permission), I think you had two separate "events" for each weekday meeting. By the way, the links to the original, paused events are pinned to the #shf-project Slack channel, if you want to just restart them through there.

**Comment by patmbolger** [comment]
@FedericoEsparza - ah, of course ..... that is some smart software you guys have built!
