### ISSUE TITLE
Remove Grape and use rails api only.

### ISSUE THREAD

**Issue by ciremoussadia** [AgileVentures/WebsiteOne#3217]
Remove Grape dependency and make the application an API only rails app.

## Expected Behavior

Rails 5 is great for creating an API so it would be easier to maintain.

We just need to turn the existing application into an api-only.

## Current Behavior
We're using Grape to help build the API. These adds a level of dependency and complexity as we need to learn about Grape. The WebsiteOne backend predicted to be full API to serve the frontend that will be full React.

So let me know what you think about it.

**Comment by NickSchimek** [comment]
I like this idea. I would believe switching it to a backend API would need to be done in iterations unless there is already a fully functioning frontend that would consume it. 

btw: Rails 6 is out too 😉

**Comment by NickSchimek** [comment]
I just saw the conversation you had with @tansaku regarding this, and would like to add I've built a small API using Rails 5.2 and it was straightforward and very simple. I had also taken a look at the Grape API at that time too since someone recommended it, but I found Rails much easier to implement than Grape especially since I already knew the Rails language and architecture.

**Comment by NickSchimek** [comment]
Also less dependencies in the code base are more secure and will require less maintenance overhead in the future.

**Comment by tansaku** [comment]
great discussion here @NickSchimek and @ciremoussadia 

@nisevi would love to get your input on this ... :-)

**Comment by aonomike** [comment]
There was talk of starting from the ground up a rails only api in our chat with @mattwr18 and @ciremoussadia , Any thoughts?
