### ISSUE TITLE
New Directions for WSO

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/WebsiteOne#721]
From Slack Chat:
Sam Joseph [9:16 AM] 
@diraulo: so continuing our discussions about WSO we could really use someone to take an active project management role here

we've also got a question about direction
Free Code Camp seem to be making a big splash with things like this: <http://freecodecamp.com/stories>

but there's is much more accessible and the pictures of people really help

Sam Joseph [9:17 AM]
of course FCC is a different proposition - start from nothing and work your way up where as we are currently focused on people who are already programmers to start with

We have a number of directions we could take:
1) Adjust AgileVentures to focus on helping those with zero programming experience
2) Do a new version of WSO but still focused on experienced programmers, but with a tighter focus that the current site
3) leave the current site as it is and focus on a separate site like Web site two that focuses on bringing in charities and non-profits
4) something else, different direction entirely ...
5) focus on upgrading the existing site by improving performance, removing some features and smoothing the pair programming event stuff that the MOOCers are about to use ...

**Comment by sidhene** [comment]
Unless things have changed a lot since Dec 2014, AgileVentures isn't excluding beginners. I was a beginner when I joined. I felt the community did a good job of meeting my needs.

Yes, it focuses on people who already know how to code a little bit, but I think it ought to. Yes, I had to go away and learn enough to participate but that was fine. 

There are TONS of resources available for people who are starting from zero. Helping people who know nothing is easy, because the fundamentals they need to know are very predictable (and practiced). What's hard is finding a community / project to get yourself to the next level, where your path as a developer can go in any number of directions. 

I find AV to be filling an important gap - fluent enough to participate, but not expert enough to be recruited and supported by mentors at work. No one else does this (as far as I can tell). I think AV can best serve the world by doing a great job at helping intermediates. Let the dozens of projects for beginners help the beginners, and then be there for those beginners when they outgrow those programs.

Just my two cents...

**Comment by tansaku** [comment]
thanks @sidhene really appreciate your input - your suggestions of direction and how we can do better very much appreciated ...

**Comment by simoncal-saas** [comment]
I am in agreement with @sidhene.  I feel that I need a bit more training before making a meaningful contribution to AV projects.  Hopefully that day will come soon, for me and my AV partner.

**Comment by tansaku** [comment]
we should review this as with #745 and create individual tickets

**Comment by freeranger** [comment]
This issue was moved to AgileVentures/AgileVentures#1
