### ISSUE TITLE
Accept JIRA, waffle, and links in project attributes for project management tools

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#759]
Imported from https://www.pivotaltracker.com/story/show/82015510

From Nick: " The OSRA project has recently transitioned to using JIRA rather than Pivotal Tracker for our project management. Since only Pivotal URIs are valid on AV, we cannot update the project page to reflect the change, and even if we could the page would remain hard-coded to display the text "OSRA on PivotalTracker". Is there any way to resolve this?"

**NOTE**
This does not include a separate JIRA tab similar to what we have for Pivotal Tracker

**Comment by freeranger** [comment]
I understand that the current mechanism validates that the link is a valid PT link...which failed for @thomaso recently due to the format changing.
Unless there is a compelling reason to keep this, I would suggest that you don't validate the links at all - it is the responsibility of whoever adds a link to be sure it is valid, and that way you are automatically supporting every PM tool that can be linked to on the web - you don't have to add specific validations for each one you choose to "support"
That's the beauty of html links :)

**Comment by sampritipanda** [comment]
We need to validate whether the link is a valid Pivotal Tracker link because we have a feature which displays the stories that are currently being worked on, on the project page by pulling them from pivotal's API.

**Comment by freeranger** [comment]
Ah ok, well how about this:
for "supported" PM tools you get that feature but for "unsupported" ones, well you can still put your link there but don't expect to see a list of issues being worked on?
That way I can still put my link to myfaviouritepmtool.com in the spot where the link to a pm tool appears (rather than burying it in the body of the project page as I have to do at the moment).

You can encourage people to use PT or waffle or whatever because they get better integration with WSO but it should still be easy to use another tool and have links to it....

Maybe the two need to be split - one link to the PM tool, a separate link to pull down a list of issues being worked on?  It may not be possible to derive one from the other...

**Comment by tochman** [comment]
The problem I see here is that some projects might choose tools that needs visitors to sign up. I'm not sure about Waffle, but PT projects are accessible even if you are not signed up. You just can't contribute. That is of big importance to our priciple of Open Process. 

We've had Jiira, or what have you, being used on at least one project and, as far as I'm concerned, that tool dos not support our process. 

So I would say let's be careful about this.

**Comment by freeranger** [comment]
I didn't think we had a single "process"?  In discussions with @tansaku previously, e.g. in https://github.com/AgileVentures/WebsiteOne/issues/745, I got the impression that we want to let people be free to choose the tools they use and they way in which they work...which doesn't seem compatible with having a "process" to follow.

I would prefer to see a "this is the list of tools we use, if you come on board then you use them too" approach because then there will be consistency across projects since all the tools etc are familiar and there is none of the friction associated with learning new products, maybe having to sign up for new accounts (even in PT you have to sign up if you want to actually do anything) etc, but that is not compatible with the "use what you want, how you want" approach that Sam seems to be advocating.

Don't get me wrong, I don't like being told how to work ;)  But I would accept "this is how we work here" if that meant it was easier to get up to speed and move between projects.

Somewhere is the balance between the two extremes but I'm not quite sure where that sweet spot is...

**Comment by tansaku** [comment]
@freeranger - we don't have a specified process, but we do have a commitment to "open development", i.e. that whatever project management tool you use that it's publicly visible, like your source code.

I do advocate (mostly) use what you want, how you want; but we are very strongly committed to both open source and open development.  So your source code needs to be open, and your development process needs to be open.  If people want AV support for projects with closed source or closed development then that's one thing they'd pay premium membership for.

**Comment by freeranger** [comment]
@tansaku Ok understood.  If I have to create an account to access the PM tool, but anyone can do so and see the PM process, does that count as "open development"?

Merely preventing people from setting the PM link to whatever they want doesn't actually stop them from using whatever PM tool they want (or linking to it in the body of the project description) - it just stops them from using the PM Tool link on the project page and so makes the page less useful and the project less "accessible".

**Comment by tansaku** [comment]
yes, I think that the project management link should accept any URL.  I think we need to be permissive in terms of allowing people to propose things, rather than excluding things at the URL level.

We can take up issue about closed and open access with individual projects.

**Comment by freeranger** [comment]
@tansaku Cool and the gang.
 
More generally, and perhaps this warrants a separate issue (there is one about CI specifically https://github.com/AgileVentures/WebsiteOne/issues/762), I would like to be able to add links to all sorts of different things:-
- Both of my github repos because my front end is separate to the back end
- My CI build
- My Live website(s)
- My deployed "latest trunk" 
- my slack channel

and so on...

So you maybe in the UI specify the type of link you are adding (incase we want to do anything special with it, e.g. use special icons for PM tools, repos etc) and then just the link itself, which is not validated at all and could be to anywhere...

I mentioned this somewhere before, either in "the novel" or perhaps a story that got left behind on PT

**Comment by tansaku** [comment]
Feels like there are three options here:

1. add additional tracker field
2. make existing PT field accept any link and disable activity view
3. make existing PT field accept any link and fail gracefully

**Comment by tansaku** [comment]
also I wonder can GA tell us how many people looked at http://www.agileventures.org/projects/websiteone#activity ???

**Comment by tochman** [comment]
Why would we want another field? We could just whitelist more services in the validator.

**Comment by tansaku** [comment]
we would want to avoid another field @tochman - we were just enumerating the options - I think there was general agreement in the kick off that we should go for either option 2 or 3, but we're going to sleep on which of those two is best

**Comment by freeranger** [comment]
I was thinking more along the lines of you
choose to add a link and specify which type it is incase there's something special we want to do with them, so you say "here is a link to a PM tool@ or "here is a link to a Repo" and you can have multiple of each.
Without looking at the code I guess you have a single field on a..project? record representing the PM tool link etc, where this would be a 1:many relationship between project and links
