### ISSUE TITLE
set up test coverage on pull requests

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#814]
maybe coveralls?

**Comment by tansaku** [comment]
https://coveralls.io

**Comment by diraulo** [comment]
I've had a look at this and test coverage is still pushed to coveralls. The reason we don't have it as part of PRs checks is simply because Semaphore does not work with coveralls 'Comment on pull request' feature. 

According to discussions [here](https://github.com/lemurheavy/coveralls-public/issues/396) semaphore was updated to support this feature. Not sure if coveralls now officially support semaphore.

**Comment by diraulo** [comment]
Also @tochman I need admin access to WSO profile on coveralls in order to make some changes.

**Comment by tansaku** [comment]
@diraulo I'll look into this

**Comment by diraulo** [comment]
I can't recall exactly what I did that got this working :see_no_evil:  but we now have coverage check on new PRs :smile: 

![screenshot 2016-03-08 09 37 03](https://cloud.githubusercontent.com/assets/4028374/13595107/815d1f88-e511-11e5-944b-dc1ada7b9f1a.png)

**Comment by tansaku** [comment]
thanks @diraulo - great work!
