### ISSUE TITLE
Github signup can fail if no email associated with Github profile

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#876]
We've had various reports of this ...

e.g. see https://github.com/AgileVentures/WebsiteOne/issues/778

**Comment by diraulo** [comment]
This happens when user has Public email (In github settings) setup to: 
<img width="427" alt="screenshot 2016-03-08 17 13 05" src="https://cloud.githubusercontent.com/assets/4028374/13605583/ef6be51a-e550-11e5-9011-e8a8f67ad52d.png">

@tochman pointed out that the email might available in a different field from the document returned when authentication with Github. Something to investigate.
