### ISSUE TITLE
Best approach for documenting devops?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/WebsiteOne#931]
@mtc2013 and I were testing on staging and we needed to set some env vars for managing the slack notifications including SLACK_NOTIFICATIONS and AGILE_BOT_URL and saying we thought it would be good to document this, but it was unclear where, other than to reflect they can be inferred from the code.

My big concern is about documentation going out of date, and I wondered if it made sense to have devops documentation in Cucumber like so:

``` gherkin
Feature: Slack Service
  As a site admin
  So that users can join in each others pairing sessions
  I would like them to be aware of each others activity

  Scenario: Slack Notifications
    Given that Slack Notifications are enabled  --> that the env var "SLACK_NOTIFICATIONS" is set to true
    And that the Agile Bot URL is set correctly --> that the env var "AGILE_BOT_URL" is set to "http://agilebot.herokuapp.com"
    When I start a hangout
    There should be an appropriate notification in slack
```

**Comment by freeranger** [comment]
hmm...is it any less likely to go out of date because it is a comment to a feature rather than a separate document?
The cucumber tests themselves are living documnetation...can't I just look at the code behind `Given that Slack Notifications are enabled` and see that the environment variable is set to true there?

**Comment by tansaku** [comment]
apologies, my example was not as clear as I would have liked.  I was using "-->" to imply a possible alternative statement, or the contents of the relevant step definition, not a comment, so for example: 

```gherkin
  Scenario: Slack Notifications
    Given that the env var "SLACK_NOTIFICATIONS" is set to true
    And that the env var "AGILE_BOT_URL" is set to "http://agilebot.herokuapp.com"
    When I start a hangout
    Then There should be an appropriate notification in slack
```

which would be living documentation with the necessary dev ops information exposed directly.

**Comment by freeranger** [comment]
Ah I see now where you're coming from...though the problem now is that you are exposing implementation details.
Anyone, technical or otherwise, could write the requirement
```
Given that Slack Notifications are enabled
When I start a hangout
Then There should be an appropriate notification in slack
```
but this
```
Given that the env var "SLACK_NOTIFICATIONS" is set to true
When I start a hangout
Then There should be an appropriate notification in slack
```
not only requires technical information that the client for the app wouldn't necessarily understand (and why should they?) but also it is making assumptions about how the feature will be technically implemented (since you write your features first, right?) and is now a brittle test - If you decided to switch to config files or a database to store config then this test has to change because the implementation has change, when actually the _intent_ is still the same - ie, if notificaitons are enabled, you get a notification!

Yes the supporting steps would have to change but that's ok - they are there to support the feature.  The feature itself is unchanged so why it it reliant on the implementation?

**Comment by tansaku** [comment]
it's reliant on the implementation so that the implementation is clear - it's about having the devop process more explicitly documented; but I am not so concerned about whether that's in the step name, or hidden behind a more general term.

The issue here was that we currently don't have *any* documentation about these env VARs, and I'm proposing that rather than creating more documentation that slowly dies - let's have things documented explicitly in the executable tests.  Also, at the moment the chances of the implementation changing are small, so making the process explicit is the more important issue here.

Actually I generally like cucumber scenarios to be more declarative (and want them to be implementation independent) so the mention of the ENV var can go in the step - that's a side issue here. The point I'm really proposing here is actually having some reference to these ENV vars at all.  At the moment there's no reference to them in the tests and we have the test settings turn them off by default and steps like `Given that Slack Notifications are enabled` in existing features just stub 3rd party services (unnecessarily given that they are all turned off by default in test mode) ... what's particularly misleading is that these stubs make it look like the tests are exercising the code all the way up to the 3rd party service, when actually they aren't.

The key point is that IF the env vars had been mentioned in the related tests then it would have served to help us more quickly understand other sorts of problems we encountered - but then maybe working it out from the code as we did was sufficient?  The key trouble is thinking that the tests have got us covered and then discovering that they don't because the testing setup is not as close to production as we would like ... explicitly setting the env vars in the test to match the production setup would reduce the chances of that.

However with all that said when we tried to remove the test defaults it created all sorts of trouble through the app, so addressing all this will not be open and shut ...
